version: '2'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: fishpi-mqtt
    ports:
      - '1883:1883'
      - '9001:9001'
  app:
    image: php:7.1-fpm
    volumes:
      - .:/code
  subscriber:
    image: python
    volumes:
      - .:/code
    command:
      - tail
      - -f
      - /dev/null

