version: '2'

services:
  app:
    image: php:7.1-fpm
    volumes:
      - .:/code
  subscriber:
    image: python:2.7
    volumes:
      - .:/code
    command:
      - tail
      - -f
      - /dev/null

